resources:
  - deployment.yaml

patches:
  - target:
      kind: Deployment
      name: green-app
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: dockerforbegin/iciciproject:v1
